# -*- coding: utf-8 -*-
"""KIF Streamlit/cloudfare launcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iy_6WJpwrPbSWRozrFcoTAVIIxSyLda9
"""

#Clone + install
!rm -rf KingsInvestmentFund
!git clone https://github.com/mattyyychan/KingsInvestmentFund.git
!pip -q install -r /content/KingsInvestmentFund/requirements.txt
!pip -q install cloudflared

# Enter  WRDS creds (session-only)
import os, getpass
os.environ["WRDS_USERNAME"] = input("WRDS username: ").strip()
os.environ["WRDS_PASSWORD"] = getpass.getpass("WRDS password: ")

from pathlib import Path

path = Path("/content/KingsInvestmentFund/investment_dashboard/dashboard")
path.mkdir(parents=True, exist_ok=True)

(path / "wrds_auth.py").write_text("""
from pathlib import Path
import os

WRDS_HOST = "wrds-pgdata.wharton.upenn.edu"
WRDS_PORT = "9737"
WRDS_DB   = "wrds"

def ensure_pgpass(username: str, password: str) -> None:
    pgpass = Path.home() / ".pgpass"
    line = f"{WRDS_HOST}:{WRDS_PORT}:{WRDS_DB}:{username}:{password}\\n"
    if pgpass.exists():
        existing = pgpass.read_text(errors="ignore")
        if line in existing:
            return
        pgpass.write_text(existing + ("" if existing.endswith("\\n") else "\\n") + line)
    else:
        pgpass.write_text(line)
    os.chmod(pgpass, 0o600)
""")

print("wrds_auth.py written")

from pathlib import Path
import sys

# Fix: add dashboard folder to sys.path
sys.path.append("/content/KingsInvestmentFund/investment_dashboard/dashboard")

app_path = Path("/content/KingsInvestmentFund/investment_dashboard/dashboard/app.py")
txt = app_path.read_text()

marker = "# --- WRDS auth (Colab/Deploy friendly) ---"
if marker not in txt:
    needle = "import streamlit as st"
    insert = (
        "import os\n"
        "from wrds_auth import ensure_pgpass\n\n"
        "# --- WRDS auth (Colab/Deploy friendly) ---\n"
        "WRDS_USER = None\n"
        "WRDS_PASS = None\n"
        "try:\n"
        "    WRDS_USER = st.secrets.get('wrds', {}).get('username')\n"
        "    WRDS_PASS = st.secrets.get('wrds', {}).get('password')\n"
        "except Exception:\n"
        "    pass\n"
        "WRDS_USER = WRDS_USER or os.getenv('WRDS_USERNAME')\n"
        "WRDS_PASS = WRDS_PASS or os.getenv('WRDS_PASSWORD')\n"
        "if WRDS_USER and WRDS_PASS:\n"
        "    ensure_pgpass(WRDS_USER, WRDS_PASS)\n"
        "# ----------------------------------------\n"
    )
    app_path.write_text(txt.replace(needle, needle + "\n" + insert))

print("patched:", marker in app_path.read_text())

# Commented out IPython magic to ensure Python compatibility.
# Go to dashboard folder
# %cd /content/KingsInvestmentFund/investment_dashboard/dashboard

# Run Streamlit in background
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true &>/content/streamlit.log &

# Download official Cloudflare binary (works in Colab)
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Run tunnel
!./cloudflared-linux-amd64 tunnel --url http://localhost:8501 --no-autoupdate